<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RestaurantSaaS.Workers</RootNamespace>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.15" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\RestaurantSaaS.Application\RestaurantSaaS.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\RestaurantSaaS.Infrastructure\RestaurantSaaS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
