using RestaurantSaaS.Domain.Common;
using RestaurantSaaS.Domain.Enums;
using RestaurantSaaS.Domain.Exceptions;

namespace RestaurantSaaS.Domain.Procurement;

public class Supplier : TenantAuditableEntity
{
    public string Name { get; private set; } = default!;
    public string ContactEmail { get; private set; } = default!;
    public string? ContactPhone { get; private set; }
    public bool IsActive { get; private set; } = true;

    private readonly List<PriceList> _priceLists = [];
    public IReadOnlyCollection<PriceList> PriceLists => _priceLists.AsReadOnly();

    private Supplier() { }

    public Supplier(Guid tenantId, string name, string contactEmail, string? contactPhone)
    {
        TenantId = tenantId;
        Name = name;
        ContactEmail = contactEmail;
        ContactPhone = contactPhone;
    }

    public PriceList AddPriceList(string name, DateOnly effectiveFrom, DateOnly? effectiveTo)
    {
        var list = new PriceList(TenantId, Id, name, effectiveFrom, effectiveTo);
        _priceLists.Add(list);
        return list;
    }

    public void Deactivate() => IsActive = false;
}

public class PriceList : TenantAuditableEntity
{
    public Guid SupplierId { get; private set; }
    public string Name { get; private set; } = default!;
    public DateOnly EffectiveFrom { get; private set; }
    public DateOnly? EffectiveTo { get; private set; }

    private readonly List<PriceListItem> _items = [];
    public IReadOnlyCollection<PriceListItem> Items => _items.AsReadOnly();

    private PriceList() { }

    internal PriceList(Guid tenantId, Guid supplierId, string name, DateOnly effectiveFrom, DateOnly? effectiveTo)
    {
        TenantId = tenantId;
        SupplierId = supplierId;
        Name = name;
        EffectiveFrom = effectiveFrom;
        EffectiveTo = effectiveTo;
    }

    public PriceListItem AddItem(Guid ingredientId, decimal unitPrice, decimal? discountPercent = null)
    {
        var item = new PriceListItem(Id, ingredientId, unitPrice, discountPercent);
        _items.Add(item);
        return item;
    }
}

public class PriceListItem : BaseEntity
{
    public Guid PriceListId { get; private set; }
    public Guid IngredientId { get; private set; }
    public decimal UnitPrice { get; private set; }
    public decimal? DiscountPercent { get; private set; }

    public decimal NetUnitPrice => DiscountPercent is null ? UnitPrice : UnitPrice * (1 - DiscountPercent.Value / 100m);

    private PriceListItem() { }

    internal PriceListItem(Guid priceListId, Guid ingredientId, decimal unitPrice, decimal? discountPercent)
    {
        PriceListId = priceListId;
        IngredientId = ingredientId;
        UnitPrice = unitPrice;
        DiscountPercent = discountPercent;
    }
}

public class PurchaseOrder : TenantAuditableEntity
{
    public Guid SupplierId { get; private set; }
    public Guid WarehouseId { get; private set; }
    public PurchaseOrderStatus Status { get; private set; } = PurchaseOrderStatus.Draft;
    public Guid RequestedByEmployeeId { get; private set; }
    public Guid? ApprovedByEmployeeId { get; private set; }
    public DateTimeOffset? ApprovedAt { get; private set; }
    public bool IsAutoGenerated { get; private set; }

    private readonly List<PurchaseOrderLine> _lines = [];
    public IReadOnlyCollection<PurchaseOrderLine> Lines => _lines.AsReadOnly();

    public decimal TotalAmount => _lines.Sum(l => l.Quantity * l.UnitPrice);

    private PurchaseOrder() { }

    public PurchaseOrder(Guid tenantId, Guid supplierId, Guid warehouseId, Guid requestedByEmployeeId, bool isAutoGenerated = false)
    {
        TenantId = tenantId;
        SupplierId = supplierId;
        WarehouseId = warehouseId;
        RequestedByEmployeeId = requestedByEmployeeId;
        IsAutoGenerated = isAutoGenerated;
    }

    public PurchaseOrderLine AddLine(Guid ingredientId, decimal quantity, decimal unitPrice)
    {
        if (Status != PurchaseOrderStatus.Draft) throw new DomainException("Can only add lines to a draft purchase order.");
        var line = new PurchaseOrderLine(Id, ingredientId, quantity, unitPrice);
        _lines.Add(line);
        return line;
    }

    public void SubmitForApproval() => Status = PurchaseOrderStatus.PendingApproval;

    public void Approve(Guid approvedByEmployeeId)
    {
        if (Status != PurchaseOrderStatus.PendingApproval) throw new DomainException("Only pending purchase orders can be approved.");
        Status = PurchaseOrderStatus.Approved;
        ApprovedByEmployeeId = approvedByEmployeeId;
        ApprovedAt = DateTimeOffset.UtcNow;
    }

    public void MarkOrdered() => Status = PurchaseOrderStatus.Ordered;

    public void ReceiveLine(Guid lineId, decimal receivedQuantity)
    {
        var line = _lines.SingleOrDefault(l => l.Id == lineId) ?? throw new DomainException("Purchase order line not found.");
        line.Receive(receivedQuantity);
        Status = _lines.All(l => l.IsFullyReceived) ? PurchaseOrderStatus.Received : PurchaseOrderStatus.PartiallyReceived;
    }

    public void Cancel() => Status = PurchaseOrderStatus.Cancelled;
}

public class PurchaseOrderLine : BaseEntity
{
    public Guid PurchaseOrderId { get; private set; }
    public Guid IngredientId { get; private set; }
    public decimal Quantity { get; private set; }
    public decimal UnitPrice { get; private set; }
    public decimal ReceivedQuantity { get; private set; }

    public bool IsFullyReceived => ReceivedQuantity >= Quantity;

    private PurchaseOrderLine() { }

    internal PurchaseOrderLine(Guid purchaseOrderId, Guid ingredientId, decimal quantity, decimal unitPrice)
    {
        PurchaseOrderId = purchaseOrderId;
        IngredientId = ingredientId;
        Quantity = quantity;
        UnitPrice = unitPrice;
    }

    internal void Receive(decimal quantity) => ReceivedQuantity += quantity;
}

public class GoodsReceipt : TenantAuditableEntity
{
    public Guid PurchaseOrderId { get; private set; }
    public Guid ReceivedByEmployeeId { get; private set; }
    public DateTimeOffset ReceivedAt { get; private set; }
    public string? Notes { get; private set; }

    private GoodsReceipt() { }

    public GoodsReceipt(Guid tenantId, Guid purchaseOrderId, Guid receivedByEmployeeId, string? notes)
    {
        TenantId = tenantId;
        PurchaseOrderId = purchaseOrderId;
        ReceivedByEmployeeId = receivedByEmployeeId;
        ReceivedAt = DateTimeOffset.UtcNow;
        Notes = notes;
    }
}
